package com.ua.hiah.service.source.database;

import com.ua.hiah.model.CDMVersion;
import com.ua.hiah.model.source.SourceDatabase;
import com.ua.hiah.model.source.SourceTable;
import org.springframework.web.multipart.MultipartFile;

public interface SourceDatabaseService {

    /**
     * Reads Scan report generated by White Rabbit and persists its information
     *
     * @param name EHR database name
     * @param file Scan report file
     * @return Source Database (with its tables, fields and value counts)
     */

    SourceDatabase createDatabaseFromScanReport(String name, MultipartFile file);


    /**
     * Creates and persists the content of an EHR database contained in a JSON file
     *
     * @param sourceDatabase EHR database stored in JSON file
     * @return created source database
     */

    SourceDatabase createDatabaseFromJSON(SourceDatabase sourceDatabase);

    SourceTable createSourceStemTable(CDMVersion version, SourceDatabase sourceDatabase);
}
