package com.ua.hiah.service.source.database;

import com.ua.hiah.model.CDMVersion;
import com.ua.hiah.model.source.SourceDatabase;
import com.ua.hiah.model.source.SourceTable;
import org.springframework.web.multipart.MultipartFile;

public interface SourceDatabaseService {

    /**
     * Reads Scan report generated by White Rabbit and persists its information
     *
     * @param name EHR database name
     * @param file Scan report file
     * @return Source Database (with its tables, fields and value counts)
     */

    SourceDatabase createDatabaseFromScanReport(String name, MultipartFile file);


    /**
     * Creates and persists the content of an EHR database contained in a JSON file
     *
     * @param sourceDatabase EHR database stored in JSON file
     * @return created source database
     */

    SourceDatabase createDatabaseFromJSON(SourceDatabase sourceDatabase);


    /**
     * Adds stem table to EHR database and its mappings (contained in file)
     *
     * @param version OMOP CDM version
     * @param sourceDatabase EHR database object
     * @return altered source database
     */

    SourceTable createSourceStemTable(CDMVersion version, SourceDatabase sourceDatabase);


    /**
     * Remove stem table from EHR database
     *
     * @param table stem table
     */

    void removeTable(SourceTable table);
}
