version: '3.2'
services: 
  postgres:
    image: postgres
    ports:
      - 5432:5432 
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hiah
  backend:
    build: 
      context: backend/hiah
      dockerfile: Dockerfile.DEV
    environment: 
      CONFIG_FILE: "application-dev.properties"
      PROFILE: "dev"
    ports:
      - 8100:8000
  frontend:
    build: 
      context: frontend
      dockerfile: Dockerfile.DEV
    ports:
      - 3000:3000
