version: '3.2'
services: 
  postgres:
    image: postgres
    ports:
      - 5432:5432 
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: riah
  backend:
    build: 
      context: backend/riah
      dockerfile: Dockerfile
    environment: 
      CONFIG_FILE: "application.properties"
      PROFILE: "runtime"
    ports:
      - 8081:8081
  frontend:
    build: 
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000