version: '3.2'
services: 
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432 
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: riaw
  backend:
    container_name: backend
    build: 
      context: backend/riaw
      dockerfile: Dockerfile.DEV
    environment: 
      CONFIG_FILE: "application-dev.properties"
      PROFILE: "dev"
    ports:
      - 8100:8000
    depends_on: 
      - "postgres"
  frontend:
    container_name: frontend
    build: 
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - ./frontend:/app
    depends_on: 
      - "backend"
    expose: 
      - "3000"
  nignx:
    container_name: nignx
    image: nginx:latest
    ports: 
      - "80:3000"
    depends_on: 
      - frontend
    volumes:
      - ./nginx:/etc/nginx/conf.d
    links: 
      - frontend
