FROM maven:3.5.2-jdk-8 AS build
COPY . /tmp/
WORKDIR /tmp/
RUN mvn clean package -Dmaven.test.skip=true

FROM adoptopenjdk/openjdk8:jre
WORKDIR /app
COPY --from=0 /tmp/target/riaw-0.0.1-SNAPSHOT.jar riaw.jar
COPY src/main/resources /app
COPY run.sh /app
ENV CONFIG_FILE=application-dev.properties
ENV APP=riaw
ENV PROFILE=dev
ENTRYPOINT ["sh", "run.sh"]
