package databaseReader;

/*
 * Handles the database reading operations:
 *  - reading scan files generated by the White-Rabbit
 *  - reading the SCV files with the OMOP CDM information
 *
 * Based on the rabbit-core module (https://github.com/OHDSI/WhiteRabbit/tree/master/rabbit-core)
 */